services:
  - type: web
    name: music-library
    env: node
    region: frankfurt
    plan: free
    buildCommand: npi ci
    startCommand: npm run migrate && node index.js
    envVars: 
      key: PGDATABASE
      fromDatabase: music-library-database
      property: database
    - key: PGUSER
      fromDatabase: music-library-database
      property: user
    - key: PGPASSWORD
      fromDatabase: music-library-database
      property: password
    - key: PGHOST
      fromDatabase: music-library-database
      property: host
    - key: PGPORT
      fromDatabase: music-library-database
      property: port

  databases:
    name: music-library-database
    plan: free
    region: frankfurt
    databaseName: music-library
    ipAllowList:[]
